[package]
name = "firedancer-agave-quic-blaster"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
env_logger = "0.11"
rand = "0.8.5"
solana-connection-cache = "2.1.2"
solana-client = "2.1.2"
